export const GET_OVERVIEW = "GET_OVERVIEW"
export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_NEWS = "GET_NEWS"
export const GET_ALL_NEWS = "GET_ALL_NEWS"
export const GET_NEW_CASES = "GET_NEW_CASES"
export const TOGGLE_OVERVIEW = "TOGGLE_OVERVIEW"
